### ISSUE TITLE
When ProtoStore fails to find a record, a very long message is generated

### ISSUE THREAD

**Issue by jeyhun** [vmware-labs/multi-tenant-persistence-for-saas#42]
### Is your feature request related to a problem? Please describe.

When ProtoStore fails to locate a record, a message is printed that contains all the fields of the DB table, including `CreatedAt`, `UpdatedAt`, `DeletedAt` columns' values. 

```
ERRO[2023-07-05T19:14:34.727] Unable to locate record [record=&{Id:some-id Msg:[] ParentId: Revision:0 OrgId:some-org-id InstanceId: CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:{Time:0001-01-01 00:00:00 +0000 UTC Valid:false} XTableName:configs}]

```

### Describe the solution you'd like

Only the columns that constitute primary key should be printed in this situation.

**Comment by krishnamiriyala** [comment]
@jeyhun Can you add sample log from unit-tests for reference

**Comment by jeyhun** [comment]
> @jeyhun Can you add sample log from unit-tests for reference

Added
