### ISSUE TITLE
Expose external transaction support for datastore methods 

### ISSUE THREAD

**Issue by gaurav-vmware** [vmware-labs/multi-tenant-persistence-for-saas#49]
### Is your feature request related to a problem? Please describe.

To support transaction boundaries single transaction need to be created and should be pass to all the CRUD method invoke as a part this transaction.

Current implementation creates new transaction forever method invoke. 

Transaction boundaries can include multiple table and row updates, delete or new insert. 

### Describe the solution you'd like

Transaction can be part of tenant context and if tenant context has transaction then datastore should use it and avoid creating new transaction.

**Comment by krishnamiriyala** [comment]
@gaurav-vmware's fix can be used for creates and upserts only. Find/Update/Delete will need to more fixes, so the PR still needs to be open.
